package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-92
=> EDU-92 Update to latest educandu package

CODEOWNERS, gulpfile.js
Closes https://educandu.atlassian.net/browse/EDU-110
=> EDU-110 Update inlets docker image to use own and adjust run arguments for macOS

package.json, src/bundles/edit-bundle.js, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-128
=> EDU-128 Update educandu

gulpfile.js
Closes https://educandu.atlassian.net/browse/EDU-134
=> EDU-134 Await for child process to gracefully shut down

package.json, src/polyfills.js, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-131
=> EDU-131 Update educandu

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-1
=> OMA-1 Update educandu

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-3
=> OMA-3 Update educandu

.github/workflows/ci.yml, Dockerfile, package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-5
=> OMA-5 Move to latest node.js version

package.json, src/bundles/bundle-config.js, src/bundles/page-template.js, src/bundles/page-template.less, src/bundles/site-logo.js, src/bundles/site-logo.less, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-6
=> OMA-6 Update educandu and set up site logo

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-7
=> OMA-7 Update educandu

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-8
=> OMA-8 Update educandu to revision 43236a9

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-9
=> OMA-9 Update educandu

package.json, src/articles-controller.js, src/index.js, yarn.lock
Closes: https://educandu.atlassian.net/browse/OMA-10
=> OMA-10 Update educandu and add an articles controller

.github/workflows/ci.yml
Closes https://educandu.atlassian.net/browse/OMA-13
=> OMA-13 Change Octopus deployment server

gulpfile.js
Closes https://educandu.atlassian.net/browse/OMA-11
=> OMA-11 Wait for child process to exit when stopping gulp

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-14
=> OMA-14 Update educandu to v0.6.0

src/bundles/page-template.less, src/main.less
Closes https://educandu.atlassian.net/browse/OMA-15
Looks like this:
=> OMA-15 Change colors

package.json, src/bundles/page-template.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-17
=> OMA-17 Update educandu to v0.7.2

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-18
=> OMA-18 Update to educandu v0.7.3

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-19
=> OMA-19 Update educandu to v0.7.4

gulpfile.js, package.json, src/bundles/page-template.js, src/bundles/page-template.less, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-20
=> OMA-22 Update educandu to v0.8.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-22
=> OMA-22 Update educandu to v0.9.0

package.json, yarn.lock
Closes: https://educandu.atlassian.net/browse/OMA-23
=> OMA-23 Update to educandu v0.10.0

package.json, src/index.js, yarn.lock
Close https://educandu.atlassian.net/browse/OMA-25
=> OMA-25 Update educandu to v0.11.0

package.json, src/bundles/page-template.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-27
=> OMA-27 Update educandu to v0.12.0 and adjust page template accordingly

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-28
=> OMA-28 Update educandu to v0.13.0

package.json, src/bundles/page-template.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-31
=> OMA-31 Update educandu to v0.15.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-32
=> OMA-32 Update educandu to v0.15.2

package.json, src/bundles/page-template.js, src/bundles/page-template.less, src/bundles/site-logo.js, src/bundles/site-logo.less, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-36
=> OMA-36 Adjust styles to work on smaller devices

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-35
=> OMA-35 Update educandu to v0.18.0

package.json, src/bundles/page-template.js, src/bundles/page-template.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-37
=> OMA-37 Update educandu to v0.19.1

package.json, src/bundles/page-template.js, src/bundles/page-template.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-38
=> OMA-38 Update educandu to v0.20.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-40
=> OMA-40 Update educandu to v0.22.0

package.json, src/bundles/bundle-config.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-46
=> OMA-46 Update educandu to v0.25.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-48
=> OMA-48 Update educandu to v0.26.1

package.json, src/bundles/home-page-template.js, src/bundles/home-page-template.less, src/bundles/page-footer.less, src/bundles/page-header.js, src/bundles/page-header.less, src/bundles/page-template.js, src/bundles/page-template.less, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-52
and looks like this:
=> OMA-52 Update educandu to v0.28.0

src/bundles/home-page-template.js, src/bundles/home-page-template.less, src/index.js, src/local-resources.json
Closes https://educandu.atlassian.net/browse/OMA-56
and looks as follow:
=> OMA-56 Change home page texts rendering

package.json, src/bundles/home-page-template.less, src/bundles/page-header.js, src/bundles/page-template.js, src/bundles/site-logo.less, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-57
=> OMA-57 Update educandu to v0.30.0

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-58
=> OMA-58 Update educandu to v0.31.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-60
=> OMA-60 Update educandu to v0.32.0

package.json, src/bundles/page-header.js, src/resource-overrides.json, yarn.lock
Close https://educandu.atlassian.net/browse/OMA-59
=> OMA-59 Update educandu to v0.33.0

gulpfile.js, package.json, src/bundles/home-page-template.js, src/bundles/page-template.js, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-64
=> OMA-64 Update educandu to v0.34.1

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-66
=> OMA-66 Update educandu to v0.34.3

package.json, src/bundles/page-template.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-67
=> OMA-67 Update educandu to v0.35.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-68
=> OMA-68 Update educandu to v.0.36.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-69
=> OMA-69 Update educandu to v0.37.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-70
=> OMA-70 Update educandu to v0.38.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-71
=> OMA-71  Update educandu to 0.39.2

package.json, src/bundles/page-footer.js, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-72
=> OMA-72 Update educandu to v0.40.0

.github/workflows/ci.yml, README.md, gulpfile.js, package.json
References https://educandu.atlassian.net/browse/OMA-73
=> OMA-73 Rename repository to oma-web

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-74
=> OMA-74 Update educandu to v0.41.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-75
=> OMA-75 Update educandu to v0.42.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-81
=> OMA-81 Update educandu to v0.48.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-82
=> OMA-82 Update educandu to v0.49.0

package.json, src/bundles/page-header.js, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-83
=> OMA-83 Update educandu to v0.50.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-84
=> OMA-84 Update educandu to v0.51.0

package.json, src/bundles/page-template.js, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-86
=> OMA-86 Update educandu to v0.53.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-87
=> OMA-87 Update educandu to v0.54.0

package.json, src/polyfills.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-89
=> OMA-89 Update educandu to v0.55.0

package.json, src/bundles/page-footer.js, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-90
=> OMA-90 Update educandu to v0.56.0

package.json, yarn.lock
Swiftly closes https://educandu.atlassian.net/browse/OMA-93
=> OMA-93 Update educandu to v0.58.0

gulpfile.js, package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-94
=> OMA-94 Update educandu to v0.59.0

src/resource-overrides.json
Closes https://educandu.atlassian.net/browse/OMA-95
=> EDU-95 Fix registration and password reset emails

package.json, src/resource-overrides.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-96
=> OMA-96 Update educandu to v0.60.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-98
=> OMA-98 Update educandu to v0.61.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-97
=> OMA-97 Update dev-tools to v3.0.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-99
=> OMA-99 Update educandu to v0.62.0

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-100
=> OMA-100 Update educandu to v0.63.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-101
=> OMA-101 Update educandu to v0.64.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-103
=> OMA-103 Update educandu to v0.65.1

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-104
=> OMA-104 Update educandu to v0.66.0

package.json, src/resource-overrides.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-105
=> OMA-105 Update educandu to v0.67.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-107
=> OMA-107 Update educandu to v0.68.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-108
=> OMA-108 Update educandu to v0.69.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-109
=> OMA-109 Update educandu to v0.70.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-110
=> OMA-110 Update educandu to v0.71.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-112
=> OMA-112 Update educandu to v0.72.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-114
=> OMA-114 Update educandu to v0.72.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-115
=> OMA-115 Update educandu to v0.73.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-116
=> OMA-116 Update educandu to v0.74.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-117
=> OMA-117 Update educandu to v0.75.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-118
=> OMA-118 Update educandu to v0.76.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-119
=> OMA-119 Update educandu to v0.77.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-125
=> OMA-125 Update educandu to v0.82.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-126
=> OMA-126 Update educandu to v0.83.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-127
=> OMA-127 Update educandu to v0.84.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-129
=> OMA-129 Update educandu to v0.85.3

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-132
=> OMA-132 Update educandu to v0.88.0

gulpfile.js, package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-133
[OMA-133]: https://educandu.atlassian.net/browse/OMA-133?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OMA-133 Update educandu to v0.88.2

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-134
=> OMA-134 Update educandu to v0.89.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-135
=> OMA-135 Update educandu to v0.90.0

.eslintrc.cjs, gulpfile.js, package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-136
=> OMA-136 Update educandu to v0.91.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-137
=> OMA-137 Update educandu to v0.92.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-138
=> OMA-138 Update educandu to v0.92.1

package.json, src/bundles/home-page-template.js, src/bundles/page-footer.js, src/bundles/page-footer.less, src/bundles/page-template.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-139
=> OMA-139 Gladly update educandu to the much nicer version 0.93.0

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-140
=> OMA-140 Update educandu to v0.94.0

src/resource-overrides.json
Closes https://educandu.atlassian.net/browse/OMA-141
=> OMA-141 Fix registration email translations

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-144
=> OMA-144 Update educandu to v0.96.0

gulpfile.js, package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-146
=> OMA-146 Update educandu to v0.97.1

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-1107
=> OMA-147 Update educandu to v0.98.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-148
=> OMA-148 Update educandu to v0.99.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-149
=> OMA-149 Update educandu to v0.100.0

package.json, src/bundles/page-header.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-150
=> OMA-150-Update-educandu-to-v0.101.1

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-154
=> OMA-154 Update educandu to v0.105.0

gulpfile.js, package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-155
=> OMA-155 Update educandu to v0.106.0

.eslintrc.cjs, package.json, src/custom-resolvers.js, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-159
=> OMA-159 Add external piano plugin

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-163
=> OMA-163 Update educandu to v0.110.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-164
=> OMA-164 Update educandu to v0.111.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-165
=> OMA-165 Update educandu to v0.112.0 (plus a minor patch)

package.json, src/custom-components/page-header.js, src/custom-components/page-header.less, src/custom-components/page-template.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-166
=> OMA-166 Update educandu to v0.113.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-162
=> OMA-162 Enable Windows build

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-167
=> OMA-167 Update educandu to v0.114.0

package.json, yarn.lock
=> piano plugin v1.0.1

package.json, src/custom-components/page-template.js, src/custom-components/page-template.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-168
=> OMA-168 Update educandu to v0.115.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-169
=> OMA-169 Update educandu to v0.116.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-171
=> OMA-171 Update educandu to v0.118.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-172
=> OMA-172 Update educandu to v0.119.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-173
=> OMA-173 Update educandu to v1.0.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-174
=> OMA-174 Update educandu to v1.1.1

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-175
=> OMA-175 Update educandu to v1.2.0

package.json, yarn.lock
Closes [OMA-176](https://educandu.atlassian.net/browse/OMA-176)
[OMA-176]: https://educandu.atlassian.net/browse/OMA-176?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> OMA-176 Update educandu to v1.3.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-178
=> OMA-178 Update educandu to v1.5.0

package.json, src/index.js, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-179
=> OMA-179 Update educandu to v1.6.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-180
=> OMA-180 Update educandu to v1.7.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-181
=> OMA-181 Update educandu to v1.8.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-182
=> OMA-182 Update educandu to v1.9.0

package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-184
=> OMA-184 Update educandu to v1.11.1

package.json, src/custom-resolvers.js, src/index.js, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/OMA-192
=> OMA-192 Update educandu to v3.0.0 and temporarily remove piano plugin

.github/workflows/ci.yml, Dockerfile, gulpfile.js, package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-1593
=> EDU-1593 Update educandu dependencies (incl. node 20)

.github/workflows/ci.yml
Closes https://educandu.atlassian.net/browse/EDU-1620
=> EDU-1620 Remove automatic Staging deployment from Github workflow

.eslintrc.cjs, package.json, src/custom-resolvers.js, src/index.js, src/main.less, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-1640
=> EDU-1640 Integrate progression models plugin (and fix react infinite render in plugin edit mode with locking rc-resize-observer version)

.github/workflows/ci.yml, package.json, yarn.lock
Closes https://educandu.atlassian.net/browse/EDU-1756
=> EDU-1756 Update dev-tools to v14.3.0
